### ISSUE TITLE
Remove unused/unsupported branches from repos

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#97] opened 2023-11-02 15:17 UTC
Since it was forked from the upstream ros2 repo, the space-ros repo has a large number of branches we do not maintain nor support and should be removed to avoid confusion.

**Comment by ivanperez-keera** [comment] 2023-11-04 17:24
Absolutely support this idea.

**Comment by ivanperez-keera** [comment] 2023-11-16 21:46
So, my approach at this would be to do, in order:
- [ ] Remove any branches that have already been merged.
- [ ] Remove any stale branches that already exist in the parent repository `ros2` and are in sync with it (meaning specifically that they are not ahead of the corresponding branch in `ros2`).
- [ ] Discuss the remaining branches with the people involved and/or the rest of the team in Technical Meetings.

Please let me know if you see an issue with this. Tagging @Bckempa @EzraBrooks @mkhansenbot for awareness.

**Comment by ivanperez-keera** [comment] 2023-12-14 17:52
First batch of branches to remove.

The following branches are identified as belonging to the parent repo and not needed in this repo:

- https://github.com/space-ros/space-ros/tree/typed-ast-archives
- https://github.com/space-ros/space-ros/tree/numpy-archives
- https://github.com/space-ros/space-ros/tree/netifaces-archives
- https://github.com/space-ros/space-ros/tree/mjeronimo/test-ament-cobra
- https://github.com/space-ros/space-ros/tree/maintenance-scripts/add-bot-admin-script
- https://github.com/space-ros/space-ros/tree/maintenance_scripts
- https://github.com/space-ros/space-ros/tree/lxml-archives
- https://github.com/space-ros/space-ros/tree/galactic-release (this is one commit _behind_ but, since we made no changes on our side, it still belongs in their repo).
- https://github.com/space-ros/space-ros/tree/galactic (this is 7 commits _behind_ but, since we made no changes on our side, it still belongs in their repo).
- https://github.com/space-ros/space-ros/tree/foxy-release (this is 5 commits _behind_ but, since we made no changes on our side, it still belongs in their repo).
- https://github.com/space-ros/space-ros/tree/foxy (this is 4 commits _behind_ but, since we made no changes on our side, it still belongs in their repo).
- https://github.com/space-ros/space-ros/tree/eloquent-release
- https://github.com/space-ros/space-ros/tree/eloquent-cyclone-master
- https://github.com/space-ros/space-ros/tree/dashing-release
- https://github.com/space-ros/space-ros/tree/dashing-pin-cyclone
- https://github.com/space-ros/space-ros/tree/dashing
- https://github.com/space-ros/space-ros/tree/crystal-release
- https://github.com/space-ros/space-ros/tree/crystal
- https://github.com/space-ros/space-ros/tree/cryptography-archives
- https://github.com/space-ros/space-ros/tree/bouncy
- https://github.com/space-ros/space-ros/tree/ardent

Please give me a thumbs up if you are ok with removing these from the `space-ros` repo.

Tagging @mkhansenbot @EzraBrooks @Bckempa

**Comment by ivanperez-keera** [comment] 2023-12-16 16:51
I'll get rid of these branches soon. I see a thumbs up from Ezra. @mkhansenbot @Bckempa if you have any comments, let me know.

**Comment by ivanperez-keera** [comment] 2023-12-17 02:04
Note: I've taken a backup of all of space-ros prior to erasing branches, just in case. I'll keep it for a couple of weeks.

A few additional branches that should go:
- https://github.com/space-ros/space-ros/tree/opencv-archives
- https://github.com/space-ros/space-ros/tree/nuclearsandwich/desktop_repos
- https://github.com/space-ros/space-ros/tree/eloquent

Since I have a backup and the logic is the same as before, I'm going to go ahead and remove. If it's not right, please let me know and I'll push the branch up again.

**Comment by ivanperez-keera** [comment] 2023-12-17 02:10
Of the branches that remain but are neither `master` nor our own release branches, we have:

- https://github.com/space-ros/space-ros/tree/nuclearsandwich/spaceros/moveit2
  - This is actually up to date with the upstream in `ros2`, but the name and the commits make it look like it actually belongs here somehow belong here. I'd appreciate clarification from other team members here who may know. @EzraBrooks @mkhansenbot 

Determining what to do about other branches may take a bit more effort in some cases, so I'll pick this up again at some other time.

**Comment by ivanperez-keera** [comment] 2023-12-17 02:26
The following branch has been fully merged into space-ros, so I will eliminate it.
- https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:mjeronimo/add-rosidl-core

I was confused by the name, but the following branch is behind its matching branch in `ros2`. There are no added commits:
- https://github.com/space-ros/space-ros/tree/master

The following branches have commits that are not merged in `ros2`, but all commits pre-date space-ros (< year 2021). I consider that indication that they don't belong in this repo, even if the changes were never merged into `ros2`:

- https://github.com/ros2/ros2/compare/rolling...space-ros:space-ros:pin_foonathan_vendor
- https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:ivanpauno/pin-fastrtps-fastcdr-eloquent-2
- https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:ivanpauno/revert-%23906

**Comment by ivanperez-keera** [comment] 2023-12-17 02:35
I think the following branch can also be removed:

- https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:fix-ament-cobra-branch

The reason is that, if you look at the only file that changed in that commit, that change is already incorporated in our `main` branch (just the hash has changed):

The new hash is: a7450328b7c7ff68be245c23334ff71bed18babe.

I've also confirmed that the change is present by visual inspection of the file in question.

**Comment by ivanperez-keera** [comment] 2023-12-17 02:41
By the same logic, the following branch can be removed:
- https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:add-process-sarif

The change is also in our `main`, with the new hash: d3959f390a1c0559c4bfd4b0eab9ff8f412eab13. I've confirmed by visual inspection that the change is included in the file changed by the original commit.

**Comment by ivanperez-keera** [comment] 2023-12-17 20:47
All commits in `earthly-wrapper` have already been included in our `main` branch. This can be checked by visual inspection of the histories ():

![image](https://github.com/space-ros/space-ros/assets/1162320/7b5e610c-a2fb-480a-b0a7-e29c5caeaad9)

Obviously, checking the commit summaries is not enough, one would have to check the contents too. Rebasing `earthly-wrapper` on top of `main` just moves the pointer to point to the same commit as `main`, and all commits that were added to `earthly-wrapper` when it forked from the main branch are discarded:

```
$ git checkout earthly-wrapper 
Branch 'earthly-wrapper' set up to track remote branch 'earthly-wrapper' from 'origin'.
Switched to a new branch 'earthly-wrapper'
$ git rebase main
warning: skipped previously applied commit 5300b0b
warning: skipped previously applied commit fcbd5bc
warning: skipped previously applied commit 269ba40
warning: skipped previously applied commit 0fb80d6
warning: skipped previously applied commit cf6ae10
warning: skipped previously applied commit f001560
warning: skipped previously applied commit 5b2f01f
warning: skipped previously applied commit a04a312
warning: skipped previously applied commit 7e0fecd
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Successfully rebased and updated refs/heads/earthly-wrapper.
$ git log
commit 3cbdef39f7b0183a48720105bb040d1358e5215c (HEAD -> earthly-wrapper, tag: humble-2023.10.0, origin/main, origin/humble-2023.10.0, origin/HEAD, main)
Merge: 94740a5 def9181
Author: Matt Hansen <12618239+mkhansenbot@users.noreply.github.com>
Date:   Tue Oct 10 14:12:54 2023 -0700

    Merge pull request #93 from space-ros/remove-autogeneration-of-repos-file
    
    Remove vcs-repos Action job (#88)
```

**Comment by ivanperez-keera** [comment] 2023-12-17 20:57
I'm removing the branch:

https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:ivanpauno/pin-fastrtps-fastcdr-eloquent-2

As stated above, the commits predate space-ros. Upon further inspection, the two commits this branch includes were merged into ros2 and space-ros in separate PRs:

- https://github.com/ros2/ros2/pull/806/
- https://github.com/ros2/ros2/pull/811/

![image](https://github.com/space-ros/space-ros/assets/1162320/40d9846e-00a0-4f56-aa51-6b61a1381220)

**Comment by ivanperez-keera** [comment] 2023-12-17 21:06
I'm removing the branch:

https://github.com/space-ros/space-ros/compare/main...space-ros:space-ros:ivanpauno/revert-%23906

As stated before, the commits predate space-ros. Upon further inspection, the only commit in this branch was never included in ros2 or space-ros, but future commits seem to invalidate the change. Specifically, the commit pins the version of a library to an older version:

```patch
   eProsima/Fast-RTPS:
     type: git
     url: https://github.com/eProsima/Fast-RTPS.git
-    version: 2.0.x
+    version: 1.10.x
```

However, future commits included in ros2's `master` branch and space-ros's `main` branch bump the version further.

```patch
   eProsima/Fast-DDS:
     type: git
     url: https://github.com/eProsima/Fast-DDS.git
-    version: 2.0.x
+    version: 2.1.x
```
and
```patch
   eProsima/Fast-DDS:
     type: git
     url: https://github.com/eProsima/Fast-DDS.git
-    version: 2.1.x
+    version: 2.3.x
```

Note that the library was renamed before those updates were applied:
```patch
-  eProsima/Fast-RTPS:
+  eProsima/Fast-DDS:
     type: git
-    url: https://github.com/eProsima/Fast-RTPS.git
+    url: https://github.com/eProsima/Fast-DDS.git
     version: 2.0.x
```

Therefore, we consider the regression to 1.10.x most likely unnecessary and outdated, and we remove the branch.

**Comment by ivanperez-keera** [comment] 2023-12-17 21:09
@EzraBrooks I cannot delete the branch ivanpauno/revert-#906. I believe there is a protection rule stopping me from doing so. Could you please remove it?

**Comment by ivanperez-keera** [comment] 2023-12-17 21:13
The branch:
https://github.com/space-ros/space-ros/tree/jacob/upstream_orocos_kdl

Only contains one commit that was not included directly in `ros2`:

```
    Track upstream repository for orocos_kdl
    
    Fixes #937
```

However, an equivalent commit  was included in `ros2` in:

```
    Track upstream repository for orocos_kdl (#1208)
    
    Use vendor package instead of upstream source repository
    
    Fixes #937
    
    Signed-off-by: Jacob Perron <jacob@openrobotics.org>
```

The two commits differ in where in the file the change is added, but the behavior is the same regardless.

**Comment by ivanperez-keera** [comment] 2023-12-17 21:20
I'm removing the branch:

https://github.com/space-ros/space-ros/tree/pin_foonathan_vendor

As stated above, the commits predate space-ros. Upon further inspection, all the commits but one were included in ros2's `eloquent` branch. The remaining commit was proposed to the upstream repo here:

https://github.com/ros2/ros2/pull/892

But the discussion indicates that the solution was discarded. Therefore, this branch can be removed.

**Comment by ivanperez-keera** [comment] 2023-12-17 21:26
I'm removing the branch:

https://github.com/space-ros/space-ros/tree/nuclearsandwich/galactic/update-fastrtps-release

All but one of the changes are included in `ros2/galactic-release`. The remaining change in `nuclearsandwich/galactic/update-fastrtps-release` consists of:

```patch
   eProsima/Fast-DDS:
     type: git
     url: https://github.com/eProsima/Fast-DDS.git
-    version: v2.3.1
+    version: v2.3.4
```

However, that change seems invalidated by the next and last commit in `ros2/galactic-release`, which pins an even more modern version of Fast-DDS (partial diff only):
```patch
   eProsima/Fast-DDS:
     type: git
     url: https://github.com/eProsima/Fast-DDS.git
-    version: v2.3.1
+    version: v2.3.6
```

Therefore, this branch can be removed.

**Comment by ivanperez-keera** [comment] 2023-12-17 21:28
As stated before,  following branch is behind its matching branch in ros2. There are no added commits:

https://github.com/space-ros/space-ros/tree/master

Therefore, it is safe to remove.

**Comment by ivanperez-keera** [comment] 2023-12-17 21:32
**Finally summary**

Only two branches remain to be removed:
- https://github.com/space-ros/space-ros/tree/nuclearsandwich/spaceros/moveit2
- https://github.com/space-ros/space-ros/tree/ivanpauno/revert-%23906

My inclination would be to remove the first because it's in the upstream repo `ros2`. The latter can be removed but there's a protection rule stopping me.

Tagging @EzraBrooks @mkhansenbot @Bckempa .

**Comment by ivanperez-keera** [comment] 2023-12-18 04:45
I sent a message to Geoffrey Biggs asking for help with the permissions bit. I also mentioned other issues stalled for the same reason.

**Comment by ivanperez-keera** [comment] 2023-12-18 12:45
> The latter can be removed but there's a protection rule stopping me.

@EzraBrooks , Geoffrey has created a group giving a few of us more permissions, but I still cannot erase:

https://github.com/space-ros/space-ros/tree/ivanpauno/revert-%23906

Can you try and see if it works for you? Thanks!

**Comment by EzraBrooks** [comment] 2023-12-18 16:13
Doesn't work for me either

**Closed** 2023-12-28 17:19 UTC
Labels: release followup
